### ISSUE TITLE
[REQs 1.4]  The system shall be capable of detecting the following classes if they are present in a video frame, regardless if it is the user’s pet or not: “cat” and “dog”

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#138]

**Comment by abirshah** [comment]
Jira link user stories.
[SN-19](https://fullstack-developer.atlassian.net/browse/SN-19)
[SN-15](https://fullstack-developer.atlassian.net/browse/SN-15)
[SN-16](https://fullstack-developer.atlassian.net/browse/SN-16)
[SN-17](https://fullstack-developer.atlassian.net/browse/SN-17)

- Cat detected in the images or videos.
- Dog detected in the images or videos.

**Comment by deeppatel-11** [comment]
![dog](https://user-images.githubusercontent.com/60020321/140249060-a2206e8a-6671-4b1f-b4f5-22bc90bf3f60.jpg)
![cat](https://user-images.githubusercontent.com/60020321/140249066-634ccb03-b39e-4792-8bd2-1fd187cf8c48.jpg)

**Comment by Himehhh** [comment]
Completed and demo provided.
