### ISSUE TITLE
[REQs 1.5] The system shall use object detection methodologies to successfully detect the user’s pet.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#139]

**Comment by abirshah** [comment]
Jira link for performing object detection methodologies.
[SN-46](https://fullstack-developer.atlassian.net/browse/SN-46)
[SN-47](https://fullstack-developer.atlassian.net/browse/SN-47)
[SN-48](https://fullstack-developer.atlassian.net/browse/SN-48)
[SN-49](https://fullstack-developer.atlassian.net/browse/SN-49)
[SN-50](https://fullstack-developer.atlassian.net/browse/SN-50)
[SN-51](https://fullstack-developer.atlassian.net/browse/SN-51)
[SN-52](https://fullstack-developer.atlassian.net/browse/SN-52)
[SN-53](https://fullstack-developer.atlassian.net/browse/SN-53)
[SN-54](https://fullstack-developer.atlassian.net/browse/SN-54)
[SN-61](https://fullstack-developer.atlassian.net/browse/SN-61)

- Yolov4 algorithm used for model creation.
- Darknet is used for training.
- Coco datasets were used.

**Comment by deeppatel-11** [comment]
![image](https://user-images.githubusercontent.com/60020321/140249189-3744f668-b007-4355-a173-edc032bc9471.png)

**Comment by deeppatel-11** [comment]
![image](https://user-images.githubusercontent.com/60020321/140249283-aff5d0f3-8b1e-4f38-885b-788b9b5dd768.png)

**Comment by Himehhh** [comment]
Completed and demo provided.
