### ISSUE TITLE
[REQs 1.6] The system shall display a bounding box around the detected objects and will also display their respective class names.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#140]

**Comment by deeppatel-11** [comment]
![dog_parts](https://user-images.githubusercontent.com/60020321/140249339-365dcb0a-abdc-4859-94d8-f3b829ce14fb.jpg)
![dog](https://user-images.githubusercontent.com/60020321/140249347-dcc7290e-f743-499c-8cf7-e887b6a87263.jpg)

**Comment by Himehhh** [comment]
Completed and demo provided.
