### ISSUE TITLE
[REQs 1.7] The system should be capable of detecting the following object classes if they are present in a video frame: a “bird”, a “mailing package”, and a “person”.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#141]

**Comment by abirshah** [comment]
Jira link for user stories.
[SN-23](https://fullstack-developer.atlassian.net/browse/SN-23)
[SN-24](https://fullstack-developer.atlassian.net/browse/SN-24)
[SN-25](https://fullstack-developer.atlassian.net/browse/SN-25)

- Mailing package is detected.
- Bird is detected.
- Bounding box is placed in the detected object.
- Person is detected.

**Comment by deeppatel-11** [comment]
![cat_mail](https://user-images.githubusercontent.com/60020321/140249373-7d81d036-b877-44c2-a122-b9d7be7f2578.jpg)
![cat_bird_mouth](https://user-images.githubusercontent.com/60020321/140249376-9cae6c4f-69c3-4c92-b57e-ad45147f2981
![person](https://user-images.githubusercontent.com/60020321/140249382-dcc4b5e6-d553-4b32-b8da-b0c5d4f03395.jpg)
.jpg)

**Comment by Himehhh** [comment]
Completed and demo provided.
