### ISSUE TITLE
[REQs 1.8] Research and brainstorm best practices to use a combination of object detection and bounding box placement patterns that could help accelerate the process of instantly recognizing unique traits for any given target (that is a dog and cat) without having to constantly collect and retrain your model with a large data set for long periods of time.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#142]

**Comment by abirshah** [comment]
Jira link for user stories.
[SN-26](https://fullstack-developer.atlassian.net/browse/SN-26)
[SN-27](https://fullstack-developer.atlassian.net/browse/SN-27)

**Comment by deeppatel-11** [comment]
![cat_part](https://user-images.githubusercontent.com/60020321/140249518-05ef5946-3773-4874-a32f-6d7ae97e1c88.jpg)
![dog_parts_2](https://user-images.githubusercontent.com/60020321/140249526-4b935cdf-240d-41c2-b0b7-5e3f2fd4eb83.jpg)
![dog_parts](https://user-images.githubusercontent.com/60020321/140249532-6f0e99c2-bd23-4e8f-9a00-c73e581f4cc5.jpg)
![cat](https://user-images.githubusercontent.com/60020321/140249541-fcfe0ab9-568c-4598-9df6-f9b14fd06627.jpg)

**Comment by Himehhh** [comment]
Investigation completed.
