### ISSUE TITLE
[REQ 3.1]The system shall store video frames and data regarding each individual event where the system detected activity/movement with the motion sensor

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#207]
**_Jira link for user stories_**:
[SN-80](https://fullstack-developer.atlassian.net/browse/SN-80) 
[SN-79](https://fullstack-developer.atlassian.net/browse/SN-79) 

**_Expected Behavior_**:
- Each video frame is to be stored on the server
- Detected object to be stored in the server

**Comment by olivierXguard** [comment]
Base on the video demo provided January 31, this requirement is completed. 👍
