### ISSUE TITLE
[REQ 3.2] The video frames stored shall not be blurred

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#208]
**_Jira link for user stories_**
[SN-81](https://fullstack-developer.atlassian.net/browse/SN-81) 
[SN-82](https://fullstack-developer.atlassian.net/browse/SN-82) 

**_Expected Behavior_**:
- Video to be clear and visible so that there is no issue with seeing the videos
- Images to be clear and visible so that there is no issue with seeing pictures of the pets.

**Comment by olivierXguard** [comment]
Completed
