### ISSUE TITLE
[REQ 3.3] The video frames shall only be stored by the system if an object is detected and present in the frame.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#209]
**_Jira link for user stories_**:
[SN-83](https://fullstack-developer.atlassian.net/browse/SN-83) 

**_Expected Behavior_**:
- Only object video is to be stored on the server.

**Comment by olivierXguard** [comment]
Base on the video demo provided January 31, this requirement is completed. 👍
