### ISSUE TITLE
[REQ 3.4] The video frames shall not be stored by the system if no object is visually present in the frame.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#210]
**_Jira Link_**:
[SN-83](https://fullstack-developer.atlassian.net/browse/SN-83?atlOrigin=eyJpIjoiMzkzMGEzZjUyMWYxNDE1YzhjNjdmZDk5YWYwMGE1MzUiLCJwIjoiaiJ9)

_**Expected Behavior**_:

- If the object is not detected video frame will not be saved on the server.

**Comment by olivierXguard** [comment]
Base on the video demo provided January 31, this requirement is completed. 👍
