### ISSUE TITLE
[REQ 3.6]  The name of the class shall be displayed along with the bounding box if the object is detected but it is not the user’s pet. 

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#212]
_**Jira Link**_:
[SN-90](https://fullstack-developer.atlassian.net/browse/SN-90?atlOrigin=eyJpIjoiMWMwM2E2ODk5NTVhNDNmMmIyMmEwMThjOWE5NTJhODkiLCJwIjoiaiJ9)
[SN-91](https://fullstack-developer.atlassian.net/browse/SN-91?atlOrigin=eyJpIjoiZTJmYmYwNjRhODE2NGFlMWE4YzU2MTFkZTQ2YmRmZTEiLCJwIjoiaiJ9)

_**Expected Behavior**_:

- Rectangular bounding will be displayed in the detected pets.
- The pet's class type will be displayed on top of the bounding box. 
- The pet's name will be displayed if it is user pet.

**Comment by deeppatel-11** [comment]
**The demo for the Requirement: **

https://user-images.githubusercontent.com/60020321/159079472-bb5cf3aa-241a-4836-be84-daee2ff9e240.mp4

**Some images for image:**
![image](https://user-images.githubusercontent.com/60020321/159078649-ea193a5e-f472-49dd-91b9-1ebfb4d33260.png)
![image](https://user-images.githubusercontent.com/60020321/159078667-f4049f45-4d97-4efa-8be0-4d53b9253879.png)
![image](https://user-images.githubusercontent.com/60020321/159078679-76865902-6596-457a-aeb3-e8ce052d78cc.png)
<img width="733" alt="image" src="https://user-images.githubusercontent.com/60020321/159078499-df026696-44fc-47af-874f-90bd25dc6212.png">

**Comment by olivierXguard** [comment]
completed requirements
