### ISSUE TITLE
[REQ 3.7]  The name of the pet shall be displayed along with the bounding box if the user’s pet is recognized.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#213]
**_Jira link for user stories_**:
[SN-90](https://fullstack-developer.atlassian.net/browse/SN-90) 
[SN-91](https://fullstack-developer.atlassian.net/browse/SN-91) 

**_Expected Behavior_**:
- pet to be identified, if it is an already recognized pet.
-  Displayed owner's pet in the videos

**Comment by deeppatel-11** [comment]
The demo video:
https://user-images.githubusercontent.com/60020321/158894647-cd5c2c89-f192-4ede-9732-455a023e94e6.mp4

The demo video for Req 2.9 can be used to demo this as well.

**Comment by olivierXguard** [comment]
Completed requirements
