### ISSUE TITLE
[REQ 3.8]  The data saved of each event by the system shall include the following information (date, time, door access granted or denied, if object class recognized return the class name, if user’s pet recognized return the pet name, the frame shall be included and displayed only if it meets the criteria mentioned in the previous points of this section).

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#214]
**_Jira link for user stories_**:
[SN-92](https://fullstack-developer.atlassian.net/browse/SN-92) 
[SN-93](https://fullstack-developer.atlassian.net/browse/SN-93) 
[SN-94](https://fullstack-developer.atlassian.net/browse/SN-94) 

**_Expected Behavior_**:
- Timestamp for the saved videos in the server
- Class type of the object to be saved in the server

**Comment by olivierXguard** [comment]
Base on the video demo provided January 31, this requirement is completed. 👍
