### ISSUE TITLE
[REQ 3.9] For every event saved by the system the user will receive a notification on their mobile phone notifying them the event occurred and granting access to see the details of the event in the format mentioned above.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#215]
**_Jira link for user stories._**:
[SN-97](https://fullstack-developer.atlassian.net/browse/SN-97) 

**_Expected Behavior_**:
- Notify the mobile app when the data is saved for an object

**Comment by abirshah** [comment]
https://user-images.githubusercontent.com/43228534/159825569-3e43be01-bffe-457a-a986-9fd1655b8988.mp4

**Comment by olivierXguard** [comment]
Completed requirement
