### ISSUE TITLE
[REQ 4.1] The system shall be trained to detect the user’s pet with less than or equal to 35 pictures of the pet, with a goal in mind that the system should be trained with less than or equal to 12 pictures.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#216]
_**Jira Link**_:
[SN-102](https://fullstack-developer.atlassian.net/browse/SN-102?atlOrigin=eyJpIjoiZTVhMzc0MzE3ZmZlNDBiYTgyN2ZlYzVjNjk3YTkyNWYiLCJwIjoiaiJ9)
[SN-103](https://fullstack-developer.atlassian.net/browse/SN-103?atlOrigin=eyJpIjoiOTYyMjFjOGQ1YmViNDMyN2FlNzFiZTE2OWY3YjlhYzEiLCJwIjoiaiJ9)

**_Expected Behavior_**:

- Users need to provide 35 images of their pets.
- System training will be done with those images.
- System will be able to detect user pets.
- Improvement goal would be with 12 images.

**Comment by olivierXguard** [comment]
Perfect, requirement completed!
