### ISSUE TITLE
[REQ 4.3] The system shall be able to detect and recognize equal to or greater than 2 unique pets (dogs or cats) in case the user has more than one pet, with a goal in mind that the system should detect and recognize equal to or greater than 4 unique pets.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#218]
**_Jira Link_** : 
[SN-104](https://fullstack-developer.atlassian.net/browse/SN-104?atlOrigin=eyJpIjoiMGNmYjc2YzBmMmVlNDc0YTk5OGRlZTg3YWEwNjZkNzgiLCJwIjoiaiJ9)
[SN-105](https://fullstack-developer.atlassian.net/browse/SN-105)

_**Expected Behavior**_:

- Two user pets can be detected at the same time.
- All the user's pets will have the same access right.
- Improvement goal should be to detect 4 unique user pets.

**Comment by olivierXguard** [comment]
Completed requirement!
