### ISSUE TITLE
[REQ 2.2] the system shall grant access to a detected object by sending a signal opening the system’s door, only if the said object is recognized as the user’s pet and it has been detected at least 3 times.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#220]
_**Jira Link**_ : 
[SN-117](https://fullstack-developer.atlassian.net/browse/SN-117?atlOrigin=eyJpIjoiZTlmMGYyODk1ZGEyNDlkYWI0NGRlZWQ2ZTJkNmM0MzIiLCJwIjoiaiJ9)
[SN-118](https://fullstack-developer.atlassian.net/browse/SN-118?atlOrigin=eyJpIjoiMDRjMGE2ZTFiMGMyNGI1M2JlMzg3ZGNkZDgwZTEyNDUiLCJwIjoiaiJ9)

**_Expected Behavior_**

- User's pet has to be detected at least three times.
- Being detected three times a user pet door will open.
- An opening signal will be received to the door.

**Comment by MikeG3** [comment]
https://www.youtube.com/watch?v=c5W_LR_jaeU&ab_channel=Mike%3APlatinumAudio

**Comment by olivierXguard** [comment]
Completed requirement!
