### ISSUE TITLE
[REQ 2.3] The system shall have a minimum of an 85% success rate when detecting the user’s pet, with a goal that should reach a capacity of 95% or higher.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#221]
**_Jira Link_** : 
[SN-71](https://fullstack-developer.atlassian.net/browse/SN-71)
[SN-70](https://fullstack-developer.atlassian.net/browse/SN-70)

**_Expected Behavior_**

- Object detection accuracy initially should be 85%.
- Object detection accuracy improvement should reach 95%.
- Accuracy should be displayed on top of the bounding box.

**Comment by deeppatel-11** [comment]
The demo video:

https://user-images.githubusercontent.com/60020321/159081179-135e3c69-fe53-48df-99c3-465c0fe9bd4a.mp4

**Comment by olivierXguard** [comment]
completed requirements
