### ISSUE TITLE
[REQ 2.4] The system shall deny access to a detected object by sending a signal to keep the system’s door closed if the said object is anything but the user’s pet.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#222]
**_Jira Link_** : 
[SN-119](https://fullstack-developer.atlassian.net/browse/SN-119?atlOrigin=eyJpIjoiZDNlYTRhNzNlMzUzNDQ1OWExOTIwMmI1MjU1ZjBlNWQiLCJwIjoiaiJ9)

**_Expected Behavior_**

- User have control on door system.
- User can manually lock the door.
- User can manually open the door.

**Comment by MikeG3** [comment]
Please see the link below for a demo of Requirement 2.4

The system detects a foreign dog, which does not grant acess to the door

https://www.youtube.com/watch?v=WH6n1HwpsxU&ab_channel=Mike%3APlatinumAudio

**Comment by olivierXguard** [comment]
Completed requirement!
