### ISSUE TITLE
[REQ 2.7] the system’s door shall remain open if the user’s pet has been recognized and the motion sensor is continuously being triggered by the same object. If the 10 seconds have not passed and the motion sensor is still being triggered, and the same object is recognized via object detection, the 10-second delay to close the system door will repeat. 

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#225]
**_Jira Link_** :

[SN-121](https://fullstack-developer.atlassian.net/browse/SN-121?atlOrigin=eyJpIjoiMjA4YTU1MWYwNGYxNGY0NGI4YzdjNThmMzNlYWJlODgiLCJwIjoiaiJ9)
[SN-122](https://fullstack-developer.atlassian.net/browse/SN-122?atlOrigin=eyJpIjoiMDE4YzI1MWVhYWJkNDI4MDg2MzRmN2RlYWEzYzU3NjkiLCJwIjoiaiJ9)

_**Expected Behavior**_

- Motion sensor will be keeping a triggered open signal when the user's pet is detected and has not entered the house.
- Delay should be 10 seconds in the time frame.
- It will be increased to 10 seconds in each time.

**Comment by MikeG3** [comment]
Please see the demonstration video at the link below
https://www.youtube.com/shorts/0mUMNG2AINQ?&ab_channel=Mike%3APlatinumAudio

The video demonstrates that while the door is opened, it will remain open if the motion detector is triggered.
In the video:
1 The door is closed (the light is red)
2 The door is activated to open (the light turns green)
3 The motion detector is triggered, triggering the blue-camera-light
4 The door remains open, for the 10 second period after the Motion detector is triggered
5 The blue-camera-light turns off, the green light turns off, the red light rurns on

**Comment by olivierXguard** [comment]
Completed requirement
