### ISSUE TITLE
[REQ 2.8] The system shall identify and classify multiple objects in the video feed. (ex. 2 cats, 3 dogs, and the user’s pet, all in one frame. Their respective bounding boxes, class names, and given pet names shall be displayed to do this).

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#226]
_**Jira Link**_ :
[SN-124](https://fullstack-developer.atlassian.net/browse/SN-124?atlOrigin=eyJpIjoiMzcxNDc3NWQzNWVkNDM1OTlhODc5MGRlODg4NjU3ZTQiLCJwIjoiaiJ9)

**_Expected Behavior_**

- Differentiate between objects in the video.
- Display their name.

**Comment by deeppatel-11** [comment]
***The demo video:***
https://user-images.githubusercontent.com/60020321/160514508-b6eb9638-a0f6-478d-8f62-96b094d7100b.mp4


<img width="1548" alt="multiple" src="https://user-images.githubusercontent.com/60020321/160514450-a11cde15-a766-4307-a755-49498f25e698.png">

**Comment by olivierXguard** [comment]
Good job! completed requirement.
