### ISSUE TITLE
[REQ 2.9]  The system shall be capable of detecting 2 or more user pets at the same time.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#227]
**_Jira Link_**:
[SN-126](https://fullstack-developer.atlassian.net/browse/SN-126?atlOrigin=eyJpIjoiMDA2ZTFjMmUwYWI0NDJmNDhlNjZjYjQ1YTkyMjcyODMiLCJwIjoiaiJ9)

**_Expected Behavior_**:

-  Detect two or more objects at the same time.
-  Two or more objects at the same time.

**Comment by deeppatel-11** [comment]
The test image: 
<img width="576" alt="more_than_one_pet" src="https://user-images.githubusercontent.com/60020321/158894784-83845113-b43f-4592-8579-750abb98f708.png">

**The demo video:**
https://user-images.githubusercontent.com/60020321/158894647-cd5c2c89-f192-4ede-9732-455a023e94e6.mp4
The image below shows the console:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/60020321/158894675-8d95dc03-e1be-4b4f-9513-909f22ccfd1d.png">

**Comment by olivierXguard** [comment]
Requirement Fulfilled
