### ISSUE TITLE
[REQ 6.1] The system’s saved data specified in part 3, which includes frames of detected objects and timestamps (date, time, door access granted or denied, if object class recognized return the class name if user’s pet recognized return the pet name, frames) shall be saved in the form of a chronological list of events that shall be accessible and viewable via the mobile app.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#255]
**_Jira Link_**:
[SN-94](https://fullstack-developer.atlassian.net/browse/SN-94?atlOrigin=eyJpIjoiZDZjNTZkMTQ2YmM1NDQ2Nzk3YjI4ZTJmNmFhNmRlNjkiLCJwIjoiaiJ9)
[SN-117](https://fullstack-developer.atlassian.net/browse/SN-117?atlOrigin=eyJpIjoiZTlmMGYyODk1ZGEyNDlkYWI0NGRlZWQ2ZTJkNmM0MzIiLCJwIjoiaiJ9)
[SN-110](https://fullstack-developer.atlassian.net/browse/SN-110?atlOrigin=eyJpIjoiNWY4ODk5OGJlMDU4NGQ1OTljNmUyMjkxYjM4ZGJlNWMiLCJwIjoiaiJ9)
[SN-95](https://fullstack-developer.atlassian.net/browse/SN-95?atlOrigin=eyJpIjoiMDFiMThmMTc5Mzk0NDc1YTgwNzAxYzdjMjRmNWJkMGQiLCJwIjoiaiJ9)

_**Expected Behavior**_:

- All the detected objects are to be saved in the database.
- Data to be organized. 
- Detected object names should be saved in the database.
- Detected object class type should be saved in the database.

**Comment by abirshah** [comment]
https://user-images.githubusercontent.com/43228534/161366564-e0f97de0-4e08-4a7b-9690-b87c699b6848.mp4


Above video, you can see the information is saved in the database chronologically  with timestamp.

**Comment by olivierXguard** [comment]
Completed requirement!
