### ISSUE TITLE
[REQ 6.4] The system shall seize to save events for 10 seconds every time an event occurs. The only exception to this is when the user’s cat is recognized and granted access.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#256]
_**Jira Link**_:
[SN-121](https://fullstack-developer.atlassian.net/browse/SN-121?atlOrigin=eyJpIjoiMjA4YTU1MWYwNGYxNGY0NGI4YzdjNThmMzNlYWJlODgiLCJwIjoiaiJ9)
[SN-122](https://fullstack-developer.atlassian.net/browse/SN-122?atlOrigin=eyJpIjoiMDE4YzI1MWVhYWJkNDI4MDg2MzRmN2RlYWEzYzU3NjkiLCJwIjoiaiJ9)

**_Expected Behavior_**:

- Event should be saved after 10 seconds.
- Except for the use of pets, it should keep staying open for 10 seconds of the period.

**Comment by deeppatel-11** [comment]
**The demo video**
https://drive.google.com/file/d/1E-kBBGXRhUY2DTny-teMehke2CwOwTal/view

**Comment by olivierXguard** [comment]
Good job! Completed requirement.
