### ISSUE TITLE
[REQ 6.6] The user shall be able to opt-out of notifications.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#258]
**_Jira Link_**:
[SN-113](https://fullstack-developer.atlassian.net/browse/SN-113?atlOrigin=eyJpIjoiMGRhMjU0NDliZDEzNDFiNmI4MjdmYzE0NTMyMGEwNTgiLCJwIjoiaiJ9)

Expected Behavior:

- User should be able to leave the notification page.
- User will not be able to stuck on the notification page.

**Comment by abirshah** [comment]
https://user-images.githubusercontent.com/43228534/160508799-d81ce015-99b7-450e-8ab1-051ff5cd5914.mp4

**Comment by olivierXguard** [comment]
Completed requirement
